# Generated by Django 2.2.1 on 2021-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='产品名')),
                ('money', models.CharField(max_length=32, verbose_name='售价')),
                ('time', models.CharField(max_length=64, verbose_name='使用时长')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='产品名')),
                ('addr', models.CharField(max_length=32, verbose_name='企业名')),
                ('money', models.CharField(max_length=32, verbose_name='金额')),
                ('time_limit', models.CharField(max_length=64, verbose_name='使用期限')),
            ],
        ),
    ]
