# Generated by Django 2.2.1 on 2021-12-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20211213_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='money',
            field=models.CharField(max_length=32, verbose_name='累计消费'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=32, verbose_name='客户名称'),
        ),
    ]
